import "server-only";
import type { Product } from "../types";

type SeedProduct = Omit<Product, "deal" | "departmentId" | "departmentName" | "departmentParentId" | "stock">;

/** Catalogue source of truth. Upserted into the database on startup. */
export const SEED_PRODUCTS: SeedProduct[] = [
  {
    id: "p1",
    slug: "beatdeck-x9-android-stereo",
    name: 'BeatDeck X9 Android Stereo 9"',
    brand: "BeatDeck",
    category: "stereo",
    price: 899,
    rrp: 1299,
    rating: 4.7,
    reviews: 2381,
    fits: ["hilux", "ranger", "rav4", "corolla", "cx5", "mazda3", "i30", "triton", "dmax"],
    badge: "Bestseller",
    image: "/images/stereo-android.jpg",
    description:
      "A 9-inch HD touchscreen head unit with wireless Apple CarPlay and Android Auto, built-in DAB+ and a 32-band EQ. Ships with a vehicle-specific fascia and wiring harness so it looks factory-fitted.",
    features: ["Wireless CarPlay & Android Auto", "DAB+ digital radio", "Keeps steering-wheel controls", "Reversing camera input", "Vehicle-specific fascia included"],
  },
  {
    id: "p2",
    slug: "pulse-pro-component-speakers",
    name: 'Pulse Pro 6.5" Component Speakers',
    brand: "Pulse",
    category: "speaker",
    price: 329,
    rrp: 479,
    rating: 4.6,
    reviews: 1204,
    fits: "universal",
    badge: "Trending",
    image: "/images/speaker-component.jpg",
    description:
      "Separate woofers and silk-dome tweeters with passive crossovers for clear highs and punchy mids. The easiest big upgrade over factory door speakers.",
    features: ["100W RMS per pair", "Silk-dome tweeters", "Passive crossovers included", "Fits most front doors"],
  },
  {
    id: "p3",
    slug: "thunder-12-underseat-subwoofer",
    name: 'Thunder 12" Underseat Subwoofer',
    brand: "Thunder",
    category: "subwoofer",
    price: 699,
    rrp: 949,
    rating: 4.8,
    reviews: 876,
    fits: ["hilux", "ranger", "everest", "landcruiser", "bt50", "triton", "dmax"],
    image: "/images/subwoofer-underseat.jpg",
    description:
      "A slim powered subwoofer designed for dual-cab utes and 4WDs. Tucks under the rear seat so you keep your tray and cargo space.",
    features: ["Built-in 300W amplifier", "Under rear seat mounting", "Remote bass knob", "Custom-fit enclosure"],
  },
  {
    id: "p4",
    slug: "voltamp-4-channel-amplifier",
    name: "VoltAmp 4-Channel 1200W Amplifier",
    brand: "VoltAmp",
    category: "amplifier",
    price: 549,
    rrp: 799,
    rating: 4.5,
    reviews: 642,
    fits: "universal",
    image: "/images/amplifier.jpg",
    description:
      "Class-D four-channel amplifier that runs cool and compact. Power a full set of speakers or bridge two channels for a sub.",
    features: ["4 x 150W RMS", "Bridgeable to 2 channels", "High-level inputs for factory stereos", "Compact Class-D design"],
  },
  {
    id: "p5",
    slug: "roadeye-4k-dual-dash-cam",
    name: "RoadEye 4K Dual Dash Cam",
    brand: "RoadEye",
    category: "dashcam",
    price: 399,
    rrp: 599,
    rating: 4.6,
    reviews: 3120,
    fits: "universal",
    badge: "Hot",
    image: "/images/dashcam.jpg",
    description:
      "Front 4K and rear 1080p recording with GPS, Wi-Fi app and parking mode. Rated for Australian summer heat with a supercapacitor instead of a battery.",
    features: ["4K front + 1080p rear", "GPS speed & location", "Supercapacitor, heat resistant to 70°C", "Parking mode with hardwire kit"],
  },
  {
    id: "p6",
    slug: "ambient-rgb-interior-light-kit",
    name: "Ambient RGB Interior Light Kit",
    brand: "Lumen",
    category: "lighting",
    price: 149,
    rrp: 229,
    rating: 4.4,
    reviews: 2210,
    fits: "universal",
    image: "/images/ambient-light.jpg",
    description: "Fibre-optic ambient strips for the dash and doors, controlled from your phone. Sync to music or pick from 64 colours.",
    features: ["64 colours", "App and music sync", "Plug-and-play USB-C power", "6 metres of fibre strip"],
  },
  {
    id: "p7",
    slug: "magcharge-wireless-mount",
    name: "MagCharge 15W Wireless Mount",
    brand: "MagCharge",
    category: "mount",
    price: 89,
    rrp: 139,
    rating: 4.5,
    reviews: 4432,
    fits: "universal",
    image: "/images/phone-mount.jpg",
    description: "MagSafe-compatible magnetic mount with 15W fast wireless charging. Vent and dash clips included.",
    features: ["15W fast charging", "MagSafe compatible", "Vent and dash mounts included", "Cooling fan"],
  },
  {
    id: "p8",
    slug: "7d-luxury-floor-mats",
    name: "7D Luxury Floor Mats",
    brand: "CabinCraft",
    category: "interior",
    price: 199,
    rrp: 299,
    rating: 4.3,
    reviews: 1502,
    fits: ["rav4", "cx5", "tucson", "sportage", "outlander", "corolla", "i30", "everest"],
    image: "/images/floor-mats.jpg",
    description: "Laser-measured, raised-edge mats that trap red dust, sand and spills. Made for your exact model.",
    features: ["Laser-measured fit", "Raised waterproof edges", "Anti-slip backing", "Front and rear set"],
  },
  {
    id: "p9",
    slug: "beatdeck-mini-carplay-stereo",
    name: 'BeatDeck Mini 7" CarPlay Stereo',
    brand: "BeatDeck",
    category: "stereo",
    price: 549,
    rrp: 799,
    rating: 4.5,
    reviews: 1890,
    fits: ["corolla", "mazda3", "i30", "hilux", "ranger", "bt50"],
    badge: "New",
    image: "/images/stereo-carplay.jpg",
    description: "A compact 7-inch double-DIN with wired CarPlay and Android Auto. Great value upgrade for older utes and hatches.",
    features: ["Wired CarPlay & Android Auto", "Bluetooth hands-free", "Reversing camera input", "Double-DIN size"],
  },
  {
    id: "p10",
    slug: "pulse-coaxial-6x9-speakers",
    name: 'Pulse Coaxial 6x9" Speakers',
    brand: "Pulse",
    category: "speaker",
    price: 189,
    rrp: 279,
    rating: 4.4,
    reviews: 980,
    fits: "universal",
    image: "/images/speaker-coaxial.jpg",
    description: "Three-way 6x9 speakers for rear decks and doors. A drop-in replacement for most factory oval speakers.",
    features: ["3-way design", "90W RMS per pair", "Carbon-fibre cones", "Grilles included"],
  },
  {
    id: "p11",
    slug: "thunder-bass-tube-10",
    name: 'Thunder Bass Tube 10" Active',
    brand: "Thunder",
    category: "subwoofer",
    price: 429,
    rrp: 629,
    rating: 4.6,
    reviews: 1320,
    fits: "universal",
    image: "/images/subwoofer-tube.jpg",
    description: "An all-in-one powered bass tube. Straps into any boot and connects to factory or aftermarket stereos.",
    features: ["Built-in 250W amplifier", "High and low-level inputs", "Quick-release straps", "Wiring kit included"],
  },
  {
    id: "p12",
    slug: "lumen-matrix-led-headlights",
    name: "Lumen Matrix LED Headlights",
    brand: "Lumen",
    category: "lighting",
    price: 299,
    rrp: 449,
    rating: 4.7,
    reviews: 760,
    fits: ["hilux", "ranger", "landcruiser", "rav4", "cx5", "triton", "tucson"],
    image: "/images/headlights.jpg",
    description: "ADR-compliant LED headlight upgrade with a sharp cut-off, so you see further on country roads without dazzling oncoming traffic.",
    features: ["ADR compliant", "6500K daylight white", "Plug-and-play harness", "IP68 waterproof"],
  },
  {
    id: "p13",
    slug: "beatdeck-b12-for-bmw",
    name: 'BeatDeck B12 for BMW 12.3"',
    brand: "BeatDeck",
    category: "stereo",
    price: 1199,
    rrp: 1599,
    rating: 4.8,
    reviews: 214,
    fits: ["bmw-3-series", "bmw-x5", "bmw-1-series"],
    image: "/images/hero-interior.jpg",
    description: "Factory-look 12.3-inch screen upgrade that keeps iDrive controls, with wireless CarPlay and Android Auto.",
    features: ["Keeps iDrive controls", "Wireless CarPlay & Android Auto", "Factory-look 12.3\" screen", "Plug-and-play CAN-bus harness"],
  },
  {
    id: "p14",
    slug: "pulse-harman-upgrade-kit-bmw",
    name: "Pulse Harman Upgrade Kit for BMW",
    brand: "Pulse",
    category: "speaker",
    price: 799,
    rrp: 999,
    rating: 0,
    reviews: 0,
    fits: ["bmw-3-series", "bmw-x5"],
    image: "/images/speaker-coaxial.jpg",
    description: "Plug-and-play speaker kit for BMW factory locations.",
    features: ["Fits factory locations", "No cutting or soldering", "Centre and underseat drivers"],
  },
];

/** Admin-only product fields: [sku, department id, stock, status]. */
export const SEED_INVENTORY: Record<string, [sku: string, departmentId: string, stock: number, status: "active" | "draft"]> = {
  p1: ["BD-X9-AND", "d-stereo", 42, "active"],
  p2: ["PL-PRO-65C", "d-audio", 65, "active"],
  p3: ["TH-12-USW", "d-audio", 9, "active"],
  p4: ["VA-4CH-1200", "d-audio", 23, "active"],
  p5: ["RE-4K-DUO", "d-dashcam", 31, "active"],
  p6: ["LM-AMB-64", "d-lighting", 3, "active"],
  p7: ["MC-MAG-15W", "d-mounts", 120, "active"],
  p8: ["CC-7D-MAT", "d-interior", 27, "active"],
  p9: ["BD-MINI-7", "d-stereo", 18, "active"],
  p10: ["PL-CX-69", "d-audio", 40, "active"],
  p11: ["TH-10-TUBE", "d-audio", 0, "active"],
  p12: ["LM-MTX-LED", "d-lighting", 14, "active"],
  p13: ["BD-B12-BMW", "d-stereo", 4, "active"],
  p14: ["PL-HK-BMW", "d-audio", 6, "draft"],
};

export const SEED_TRENDING = ["p1", "p5", "p2", "p12", "p3", "p7", "p9", "p6"];

export const SEED_DEALS = [
  { productId: "p1", dealPrice: 749, claimed: 78 },
  { productId: "p4", dealPrice: 429, claimed: 54 },
  { productId: "p5", dealPrice: 319, claimed: 91 },
  { productId: "p11", dealPrice: 339, claimed: 36 },
];
